// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU8nLJF80c3fnXDW7j0z5t0TUYn_lI9-A',
    appId: '1:699064968074:web:4e36d8c5c81c44752e5e73',
    messagingSenderId: '699064968074',
    projectId: 'fitness-and-workout-c0a97',
    authDomain: 'fitness-and-workout-c0a97.firebaseapp.com',
    storageBucket: 'fitness-and-workout-c0a97.firebasestorage.app',
    measurementId: 'G-DTBNE6JXQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW41cSV6Q_YfuF9Ih900Md5Y4R4jBe3pE',
    appId: '1:699064968074:android:a6dce7a14849dd2a2e5e73',
    messagingSenderId: '699064968074',
    projectId: 'fitness-and-workout-c0a97',
    storageBucket: 'fitness-and-workout-c0a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ZYhk7wru_ePMre9lHLKIWvlriC_1F9I',
    appId: '1:699064968074:ios:2bf49111d290a5352e5e73',
    messagingSenderId: '699064968074',
    projectId: 'fitness-and-workout-c0a97',
    storageBucket: 'fitness-and-workout-c0a97.firebasestorage.app',
    iosBundleId: 'com.example.fitnessAndWorkoutPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU8nLJF80c3fnXDW7j0z5t0TUYn_lI9-A',
    appId: '1:699064968074:web:a409b4500b630bac2e5e73',
    messagingSenderId: '699064968074',
    projectId: 'fitness-and-workout-c0a97',
    authDomain: 'fitness-and-workout-c0a97.firebaseapp.com',
    storageBucket: 'fitness-and-workout-c0a97.firebasestorage.app',
    measurementId: 'G-RFCM615RYH',
  );
}
